package Modelos;
// Generated 23-jun-2017 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parqueadero generated by hbm2java
 */
public class Parqueadero  implements java.io.Serializable {


     private Integer idParqueadero;
     private String nombre;
     private String nit;
     private String direccion;
     private String telefono;
     private int cantidadPuestos;
     private String ciudad;
     private String horarioApertura;
     private String horarioCierre;
     private String logo;
     private String estado;
     private int pisos;
     private Set puestos = new HashSet(0);
     private Set trabajadors = new HashSet(0);

    public Parqueadero() {
    }

	
    public Parqueadero(String nombre, String nit, String direccion, String telefono, int cantidadPuestos, String ciudad, String horarioApertura, String horarioCierre, String logo, String estado, int pisos) {
        this.nombre = nombre;
        this.nit = nit;
        this.direccion = direccion;
        this.telefono = telefono;
        this.cantidadPuestos = cantidadPuestos;
        this.ciudad = ciudad;
        this.horarioApertura = horarioApertura;
        this.horarioCierre = horarioCierre;
        this.logo = logo;
        this.estado = estado;
        this.pisos = pisos;
    }
    public Parqueadero(String nombre, String nit, String direccion, String telefono, int cantidadPuestos, String ciudad, String horarioApertura, String horarioCierre, String logo, String estado, int pisos, Set puestos, Set trabajadors) {
       this.nombre = nombre;
       this.nit = nit;
       this.direccion = direccion;
       this.telefono = telefono;
       this.cantidadPuestos = cantidadPuestos;
       this.ciudad = ciudad;
       this.horarioApertura = horarioApertura;
       this.horarioCierre = horarioCierre;
       this.logo = logo;
       this.estado = estado;
       this.pisos = pisos;
       this.puestos = puestos;
       this.trabajadors = trabajadors;
    }
   
    public Integer getIdParqueadero() {
        return this.idParqueadero;
    }
    
    public void setIdParqueadero(Integer idParqueadero) {
        this.idParqueadero = idParqueadero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getCantidadPuestos() {
        return this.cantidadPuestos;
    }
    
    public void setCantidadPuestos(int cantidadPuestos) {
        this.cantidadPuestos = cantidadPuestos;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getHorarioApertura() {
        return this.horarioApertura;
    }
    
    public void setHorarioApertura(String horarioApertura) {
        this.horarioApertura = horarioApertura;
    }
    public String getHorarioCierre() {
        return this.horarioCierre;
    }
    
    public void setHorarioCierre(String horarioCierre) {
        this.horarioCierre = horarioCierre;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getPisos() {
        return this.pisos;
    }
    
    public void setPisos(int pisos) {
        this.pisos = pisos;
    }
    public Set getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set puestos) {
        this.puestos = puestos;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }




}


