package Modelos;
// Generated 23-jun-2017 21:03:08 by Hibernate Tools 4.3.1



/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private Integer idTrabajador;
     private Parqueadero parqueadero;
     private String nombres;
     private String apellidos;
     private String tipoDocumento;
     private String doumento;
     private String contrasena;
     private String correo;
     private String estado;

    public Trabajador() {
    }

    public Trabajador(Parqueadero parqueadero, String nombres, String apellidos, String tipoDocumento, String doumento, String contrasena, String correo, String estado) {
       this.parqueadero = parqueadero;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tipoDocumento = tipoDocumento;
       this.doumento = doumento;
       this.contrasena = contrasena;
       this.correo = correo;
       this.estado = estado;
    }
   
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public Parqueadero getParqueadero() {
        return this.parqueadero;
    }
    
    public void setParqueadero(Parqueadero parqueadero) {
        this.parqueadero = parqueadero;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDoumento() {
        return this.doumento;
    }
    
    public void setDoumento(String doumento) {
        this.doumento = doumento;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


